//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PenaltyManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RoadPenaltiesEntities1 : DbContext
    {
        public RoadPenaltiesEntities1()
            : base("name=RoadPenaltiesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int CalculateInsurance(Nullable<int> value)
        {
            /*var valueParameter = value.HasValue ? new ObjectParameter("Value", value) : new ObjectParameter("Value", typeof(int)); return value.Value * 2;

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalculateInsurance", valueParameter);*/
            return value.Value;
        }
    }
}
